---
- name: Ensure robots directory exists
  file:
    path: "{{ robots_path }}"
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: files to robots directory
  copy:
    src: "{{ item }}"
    dest: "{{ robots_path }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - robots.dissallow.txt
    - robots.dspace.txt 
