---
- name: Ensure robots directory exists
  file:
    path: "{{ nginx_robots_htdocs_path }}"
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: files to robots directory
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_robots_htdocs_path }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - robots.dissallow.txt
    - robots.dspace.txt

- name: Set default SELinux context for robots
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ nginx_robots_htdocs_path }}(/.*)?"
  become: true

- name: Restore default SELinux context for robots
  command: >
    restorecon -rv {{ nginx_robots_htdocs_path }}
  become: true
