---

- name: TLS private key directory exists
  file:
    path: "{{ nginx_key_path }}/{{ item  }}"
    state: directory
    mode: 0750
    owner: root
    group: wheel

- name: Push TLS private key
  copy:
    content: |
      {{ lookup('file', tls_cert_path + '/' + item  + '/privkey.vault.yml') }}
    dest: "{{ nginx_key_path }}/{{ item  }}/privkey.pem"
    mode: 0640
    owner: root
    group: wheel

- name: TLS cert directory exists
  file:
    path: "{{ nginx_cert_path }}/{{ item  }}"
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Push TLS Fullchain
  copy:
    src: "{{ tls_cert_path }}/{{ item  }}/fullchain.pem"
    dest: "{{ nginx_cert_path }}/{{ item  }}/fullchain.pem"
    mode: 0644
    owner: root
    group: wheel
