---

- name: Ensure robots directory exists
  file:
    path: "{{ nginx_robots_htdocs_path }}"
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: files to robots directory
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_robots_htdocs_path }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - robots.disallow.txt
    - robots.dspace.txt
    - robots.repox.txt

- name: Push Diffie Hellman ephemeral parameters
  copy:
    content: |
      {{ lookup('file', tls_cert_path + '/dhparam.vault.yml') }}
    dest: "{{ nginx_key_path }}/dhparam.pem"
    mode: 0640
    owner: root
    group: wheel

- name: Set default SELinux context for robots
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ nginx_robots_htdocs_path }}(/.*)?"
  become: true

- name: Restore default SELinux context for robots
  command: >
    restorecon -rv {{ nginx_robots_htdocs_path }}
  become: true

- include: assets-sites.yml
  with_items:
    - "{{ nginx_sites }}"
  loop_control:
    loop_var: nginx_site
  tags:
  - nginx_assets
  - nginx_assets_sites
  when: ((nginx_sites is defined) and (nginx_sites is not none))
