---

- name: Push TLS private key
  copy:
    content: !vault |
      {{ lookup('file', tls_cert_path/nginx_site.cert_name | default(nginx_site.name)/privkey.vault.yml) }}
    dest: >
      {{ nginx_cert_path }}/{{ nginx_site.cert_name | default(nginx_site.name) }}/privkey.pem
    mode: 0640
    owner: root
    group: wheel

- name: Push TLS Fullchain
  copy:
    src: >
      {{ tls_cert_path }}/{{ nginx_site.cert_name | default(nginx_site.name)/fullchain.pem }}
    dest: >
      {{ nginx_cert_path }}/{{ nginx_site.cert_name | default(nginx_site.name) }}/fullchain.pem
    mode: 0644
    owner: root
    group: wheel
