---

- name: Wildcard site config
  template:
    src: star.site.conf.j2
    dest: "/etc/nginx/conf.d/star.{{ item.name }}.conf"
  with_items: "{{ nginx_star_sites }}"
  when: ((nginx_star_sites is defined) and (nginx_star_sites is not none))

- name: Literal site config
  template:
    src: literal.site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
  with_items: "{{ nginx_literal_sites }}"
  when: ((nginx_literal_sites is defined) and (nginx_literal_sites is not none))

- name: loopback site config
  template:
    src: loopback.site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
  with_items: "{{ nginx_loopback_sites }}"
  when: ((nginx_loopback_sites is defined) and (nginx_loopback_sites is not none))

- name: Add stub site config
  template:
    src: stub.site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
  with_items: "{{ nginx_stub_sites }}"
  when: ((nginx_stub_sites is defined) and (nginx_stub_sites is not none))

- name: Add stub site config folder
  file:
    state: directory
    recurse: yes
    dest: "/srv/{{ item.name }}/etc/"
  with_items: "{{ nginx_stub_sites }}"
  when: ((nginx_stub_sites is defined) and (nginx_stub_sites is not none))

- name: Add stub site config file
  file:
    state: touch
    dest: "/srv/{{ item.name }}/etc/{{ item.name }}.nginx.conf"
  with_items: "{{ nginx_stub_sites }}"
  when: ((nginx_stub_sites is defined) and (nginx_stub_sites is not none))

- name: Set  SELinux context for stub config
  shell: |
    semanage fcontext -a -t httpd_config_t "/srv/{{ item.name }}/etc(/.*)"
    restorecon -rv "/srv/{{ item.name }}/etc/"
  with_items: "{{ nginx_stub_sites }}"
  when: ((nginx_stub_sites is defined) and (nginx_stub_sites is not none))
  become: true
