---

- name: Check for site privkey
  stat:
    path: "{{ nginx_key_path }}/{{ nginx_site.cert_name | default(nginx_site.name) }}/privkey.pem"
  register: nginx_privkeystat

- name: Check for site certificate full chain
  stat:
    path: "{{ nginx_cert_path }}/{{ nginx_site.cert_name | default(nginx_site.name) }}/fullchain.pem"
  register: nginx_fullchainstat

- name: Site config exists
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ nginx_site.name }}.conf"
    mode: 0644
    owner: nginx
    group: wheel

- name: Site config is loaded
  shell: >
     nginx -t && systemctl reload nginx
