---
# tasks file for nginx

- include: yum.yml
  become: true
  tags:
    - nginx_yum

- include: configure.yml
  become: true
  tags:
    - nginx_configure

- include: assets.yml
  become: true
  tags:
    - nginx_assets

- include: services.yml
  become: true
  tags:
    - nginx_services
