---

- name: Inital site config
  template:
    src: init.site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    force: no
  with_items: "{{ nginx_sites }}"

- name: Make sure we have acme init configs loaded
  become: true
  shell: >
     nginx -t && systemctl reload nginx
