---
- name: SSL star cert directory exists
  file:
    path: "{{ nginx_cert_path }}/star.{{ item.name }}"
    state: directory
  with_items: nginx_star_sites

- name: SSL star key directory exists
  file:
    path: "{{ nginx_key_path }}/star.{{ item.name }}"
    state: directory
  with_items: nginx_star_sites

- name: Self-signed star cert exists.
  become: true
  command: >
     openssl req -newkey rsa:2048 -nodes -sha256 -x509 
     -subj "/CN=*.{{ item.name }}" 
     -days 90 
     -keyout "{{ nginx_key_path }}"/star."{{ item.name }}"/privkey.pem 
     -out "{{ nginx_cert_path }}"/star."{{ item.name }}"/fullchain.pem
  args:
    creates: "{{ nginx_key_path }}/star.{{ item.name }}/privkey.pem"
  with_items: nginx_star_sites
