---

- name: Add nginx yum repository
  yum_repository:
    name: nginx
    description: Nginx Repository
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgkey: http://nginx.org/packages/keys/nginx_signing.key
    gpgcheck: yes
    priority: 2

- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
